### ISSUE TITLE
Icon Request :)

### ISSUE THREAD

**Issue by mhanki** [highflyer910/folder_icons_for_devs#2]
First of all, I absolutely adore your icons pack, Thea! These are so cute! 😍
I just downloaded them to bring some visual order into my projects, for which they really are perfect! Thank you so much for creating and sharing these!

I was wondering if you would maybe consider to also include a folder icon for Electron? That is the only one missing to migrate my entire projects folder to your icons, and it would be awesome to have that one too ☺️

**Comment by highflyer910** [comment]
@mhanki aww thank you, Meike! So glad you enjoy and use them ☺️ Of course, I will definitely add one for Electron today:)

**Comment by mhanki** [comment]
Thank you!! ☺️ But there is no rush, whenever you get around to it 💚

**Comment by highflyer910** [comment]
@mhanki Done!:) It only required 5-10 mins, no longer ☺️💚
